In [1]:
a = 25
print(a)
#successfully tested jupyter installation in vscode

25


In [5]:
import numpy as np
arr = np.array([11,12,13])
print(arr)
print(type(arr))
multiele = np.array([11,13,14,15, False, "Kshitij"]) #no data type limitations
print(multiele)
print(type(multiele))

[11 12 13]
<class 'numpy.ndarray'>
['11' '13' '14' '15' 'False' 'Kshitij']
<class 'numpy.ndarray'>


In [9]:
#no need to import numoy in different code sets when imported once.
arr = np.array([11,12,13,14,15.0, True, False]) # Forced type conversion to float due to 15.0
print(arr)
arr = np.array([11,12,13,14,15.0, True, False, "Kshitij"]) # No forced conversion to float, due to String data type
print(arr)

[11. 12. 13. 14. 15.  1.  0.]
['11' '12' '13' '14' '15.0' 'True' 'False' 'Kshitij']


In [12]:
#Notice the difference in print statements between a list and a Numpy array
list1 = [[11,12,13],[14,15,16]]
print(list1)
print(type(list1))
arr = np.array(list1) #example of a 2-D array using a python list
print(arr)

[[11, 12, 13], [14, 15, 16]]
<class 'list'>
[[11 12 13]
 [14 15 16]]


In [20]:
arr = np.array([[11,12,13],[14,15]])
print(arr) #np array requires a homogenous shape, depending on the data we can either use 0 or np.NaN to fill empty locations

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [21]:
arr = np.array([[11,12,13],[14,15, np.NaN]])
print(arr)

[[11. 12. 13.]
 [14. 15. nan]]
