In [1]:
a = 25
print(a)
#successfully tested jupyter installation in vscode

25


In [3]:
import numpy as np
arr = np.array([11,12,13])
print(arr)
print(type(arr))
multiele = np.array([11,13,14,15, False, "Kshitij"]) #no data type limitations
print(multiele)
print(type(multiele))

[11 12 13]
<class 'numpy.ndarray'>
['11' '13' '14' '15' 'False' 'Kshitij']
<class 'numpy.ndarray'>


In [9]:
#no need to import numoy in different code sets when imported once.
arr = np.array([11,12,13,14,15.0, True, False]) # Forced type conversion to float due to 15.0
print(arr)
arr = np.array([11,12,13,14,15.0, True, False, "Kshitij"]) # No forced conversion to float, due to String data type
print(arr)

[11. 12. 13. 14. 15.  1.  0.]
['11' '12' '13' '14' '15.0' 'True' 'False' 'Kshitij']


In [12]:
#Notice the difference in print statements between a list and a Numpy array
list1 = [[11,12,13],[14,15,16]]
print(list1)
print(type(list1))
arr = np.array(list1) #example of a 2-D array using a python list
print(arr)

[[11, 12, 13], [14, 15, 16]]
<class 'list'>
[[11 12 13]
 [14 15 16]]


In [20]:
arr = np.array([[11,12,13],[14,15]])
print(arr) #np array requires a homogenous shape, depending on the data we can either use 0 or np.NaN to fill empty locations

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [21]:
arr = np.array([[11,12,13],[14,15, np.NaN]])
print(arr)

[[11. 12. 13.]
 [14. 15. nan]]


In [4]:
list1 = [11,12,47,48,49,25,78,94] 
print(list1)
b = list1[1:5]
print(b)
print(type(b))
a = np.array(list1) # got an error, "name np is not defined", clearly because every code snippet is seperate, so unless we either 
#add the import state here (before the call, usually at the top) or run the original numpy call statement (Code Snippet 2), we will get this error. 
#notice the difference, elements in b are seperated by commas when using a list, which is not the case when using a numpy array.
print(a)
b = a[1:5]
print(b)
print(type(b))

[11, 12, 47, 48, 49, 25, 78, 94]
[12, 47, 48, 49]
<class 'list'>
[11 12 47 48 49 25 78 94]
[12 47 48 49]
<class 'numpy.ndarray'>


In [7]:
b[2] = 196
print(b)
print(a)
# inference - changing the value in b also changes the corresponding value in a, a probable example of how only one object is created in the heap,
#and multiple variables refer to it.

# to prevent the change in original data, we use the .copy() method

b = a.copy()
print(b)
print(type(b))

b[1] = 14
b[2] = 15
b[5] = 46
print(b)
print(a) #see how 'a' remains the same but 'b' changes

[ 11  12 196 196  49  25  78  94]
[ 11  12  47 196  49  25  78  94]
[ 11  12  47 196  49  25  78  94]
<class 'numpy.ndarray'>
[ 11  14  15 196  49  46  78  94]
[ 11  12  47 196  49  25  78  94]


In [9]:
arr = np.arange(9)
print(arr)
arr = np.arange(2,10,2)
print(arr)

#arange works like for loop, generating data according to the start, stop and increment
#the second arange stops at 8 which means stop value is not included.

[0 1 2 3 4 5 6 7 8]
[2 4 6 8]


In [22]:
arr.reshape(2,2)


array([[2, 4],
       [6, 8]])

In [23]:
arr.reshape(4,1)

array([[2],
       [4],
       [6],
       [8]])

In [24]:
arr.reshape(2,2) 
print(arr) #carefully observe the output of this line, the output is clearly of arr.reshape(4,1) rather than .reshape(2,2), 
#which means, .reshape does not inherently affect the original variable, whereas using arr = arr.reshape() does indeed affect arr.
arr = arr.reshape(1,4)
print(arr)
arr = arr.reshape(4,1)
print(arr)

[[2]
 [4]
 [6]
 [8]]
[[2 4 6 8]]
[[2]
 [4]
 [6]
 [8]]


In [26]:
#rehsape cna also be used to create multidimensional numpy array, eg.
arr = np.arange(1,31)
print(arr)
arr.reshape(6,5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
arr = arr.reshape(2,5,3) #3-D numpy array
#reshape needs exact product to create arrays, which means we there has to be, 6*5 = 30 elements, 2*5*3  = 30 elements, not more, not less
print(arr)
print(arr.ndim) #ndim returns the dimension of the numpy array


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]]]
3


In [32]:
#use of np.zeros, np.ones
a = np.zeros((5,5)) #need to pass the dimension as a tuple inside the fuction call
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
a + 5
#the best part about numpy arrays that make it suitable for data science applications is simple operation ways, we can easily perform the same operation,
#on multiple elements without the use of loops, well not always sometimes we do need loops, but it is much easier.

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [36]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
a * 10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [38]:
#we can also reshape multidimensional arrays
a.reshape (10,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
a = np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [51]:
a1 = np.reshape(a, (5,6), 'F')
a1

array([[ 1, 26, 22, 18, 14, 10],
       [ 6,  2, 27, 23, 19, 15],
       [11,  7,  3, 28, 24, 20],
       [16, 12,  8,  4, 29, 25],
       [21, 17, 13,  9,  5, 30]])

In [52]:
a2 = np.reshape(a, (5,6), 'C')
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [55]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [53]:
a3 = np.reshape(a, (10,3), "F")
a3

array([[ 1, 22, 14],
       [ 6, 27, 19],
       [11,  3, 24],
       [16,  8, 29],
       [21, 13,  5],
       [26, 18, 10],
       [ 2, 23, 15],
       [ 7, 28, 20],
       [12,  4, 25],
       [17,  9, 30]])

In [57]:
a4 = np.reshape(a, (10,3), 'C')
a4


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [58]:
# .T is transpose
a4.T

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [60]:
b = np.arange(9).reshape(3,3)
c = np.arange(2,11).reshape(3,3)
print(b)
print()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [61]:
#Array arithmetic operations
b+c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [62]:
b-c

array([[-2, -2, -2],
       [-2, -2, -2],
       [-2, -2, -2]])

In [63]:
b*c

array([[ 0,  3,  8],
       [15, 24, 35],
       [48, 63, 80]])

In [64]:
b/c

array([[0.        , 0.33333333, 0.5       ],
       [0.6       , 0.66666667, 0.71428571],
       [0.75      , 0.77777778, 0.8       ]])

In [65]:
b%c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
b//c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [67]:
b@c #@ denotes matrix multiplication

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])

In [68]:
#linspace gives values at equal spaces
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])